### ISSUE TITLE
SeleniumLibrary has no keyword: Wait Element Attribute Value Is

### ISSUE THREAD

**Issue by Devecor** [dashingsoft/codebang#7]
There is a keyword `Current Course Should Be` in file `util.robot`. We have to `sleep 0.2s` for waiting the animation finished. But `0.2s` is too long for program. A keyword named `Wait Element Attribute Value Is` is expected, while  SeleniumLibrary doesn't support!!!

**Comment by jondy** [comment]
一个单个的操作步骤等待`0.2`秒也是可以接受的。

另外一种解决方案是自己写一个关键字，使用 `builitin` 里面提供的循环/分支/比较语句，写了一个循环，在循环体内判断属性是否等于期望值，等于期望值的时候退出循环返回，超过一定时间没有出现期望值返回超时错误。

**Comment by jondy** [comment]
关键字的示例，可以把这个关键字放到全局公共库里面
```robot
Wait Element Attribute Value
    [Arguments]    ${Locator}    ${Name}    ${Expected Value}  

    FOR    ${index}    IN RANGE    10
        ${Value} =    Get Element Attribute    ${Locator}    ${Name}
        Exit For Loop If    ${Value} == ${Expected Value}
        Sleep 0.01
    End

    Return From Keyword     ${index} < 10
```
